#!/bin/sh

########################################################
# OSKのプロキシ設定を無効にします。										 #
# 																										 #
# Auther: Takaya Shimizu <t-shimizu@mx.omronsoft.co.jp #
# Date  : 2012/07/19																	 #
########################################################

FILE=/etc/wgetrc

sed -i -e 's/^\(h\?[ft]tps\?_proxy\)/#\1/g' $FILE

