#!/bin/sh
# $Id$
# Linearized PDF hint formatting utility.

# This definition is changed on install to match the
# executable name set in the makefile
GS_EXECUTABLE=gswin32c

OPTIONS="-P- -dSAFER -dDELAYSAFER"
while true
do
	case "$1" in
	-?*) OPTIONS="$OPTIONS $1" ;;
	*)  break ;;
	esac
	shift
done

if [ $# -ne 1 ]; then
	echo "Usage: `basename \"$0\"` input.pdf" 1>&2
	exit 1
fi

"$GS_EXECUTABLE" -q -dNODISPLAY $OPTIONS -- "`dirname \"$0\"`/dumphint.ps" "$1"
