#!/bin/sh
# $Id$

# This definition is changed on install to match the
# executable name set in the makefile
GS_EXECUTABLE=gswin32c

"$GS_EXECUTABLE" -q -P- -dSAFER -dNODISPLAY -dWRITESYSTEMDICT -- font2c.ps "$@"
