#!/bin/sh
# $Id$
# Make an AFM file from PFB / PFA and (optionally) PFM files.  Usage:
#	pf2afm fontfilename
# Output goes to fontfilename.afm, which must not already exist.
# See pf2afm.ps for more details.

# This definition is changed on install to match the
# executable name set in the makefile
GS_EXECUTABLE=gswin32c

"$GS_EXECUTABLE" -q -dNODISPLAY -P- -dSAFER -dDELAYSAFER  -- pf2afm.ps "$@"
