#!/bin/sh
# $Id$
# Print the Primary Hint Stream from a linearized PDF file.  Usage:
#	pphs filename.pdf
# Output goes to stdout.

# This definition is changed on install to match the
# executable name set in the makefile
GS_EXECUTABLE=gswin32c

"$GS_EXECUTABLE" -q -P- -dSAFER -dNODISPLAY -- pphs.ps "$@"
