#!/bin/sh
# $Id$
# Convert PostScript to PDF.

# Currently, we produce PDF 1.4 by default, but this is not guaranteed
# not to change in the future.
version=14

ps2pdf="ps2pdf$version"

"$ps2pdf" "$@"
